// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oelyccefpgnbzrvuvuhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbHljY2VmcGduYnpydnV2dWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzIxMjcsImV4cCI6MjA2MTU0ODEyN30.MVWOqn6gNV_TKKXeTlGtC-ekLU9VFhciLdKswSoBEQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);